### ISSUE TITLE
No GPS position data to ROS topic

### ISSUE THREAD

**Issue by eeroniemi** [dji-sdk/Onboard-SDK-ROS#232]
I have a problem that when launching simulator mode, and after that ROS master node, no data comes to the /dji_sdk/gps_position or /dji_sdk/gps_health except briefly while ROS master node is launching.

I have been able to reproduce this problem with two computers: 
- Linux ARM64 based mini computer (Rock64)
- Intel x64 PC

Both have latest Onboard SDK's installed:

- Onboard-SDK 3.7, commit ID d43cf0ab135b015145ab7a2e41b85cbee6522f83
- Onboard-SDK-ROS 3.7, commit ID 439a8adbd336299517faf6b18624ab457e4fb7a6

Both computers have Ubuntu 16 + ROS Kinetic. Onboard-SDK is complied with advanced sensing enabled and disabled, no difference in outcome.

M210 firmware is the latest one, v01.01.0913, date 2018-08-10. "Enable API Control" is enabled from DJI Assistant 2 SDK configuration.

## How to reproduce

Connect M210 to your PC with USB and serial.

Enable simulator mode:

```
rock64@rock64:~/dji/Onboard-SDK/utility/bin/armv8/64-bit$ ./M210ConfigTool --usb-port /dev/ttyACM0 --config-file UserConfig.txt --simulation on --latitude 60.171856 --longitude 24.915099
Read App ID
User Configuration read successfully.


STATUS/1 @ init, L55: Attempting to open device /dev/ttyUSB0 with baudrate 230400...

STATUS/1 @ init, L65: ...Serial started successfully.

STATUS/1 @ parseDroneVersionInfo, L687: Device Serial No. = 095XF7C002024S

STATUS/1 @ parseDroneVersionInfo, L689: Hardware = PM410

STATUS/1 @ parseDroneVersionInfo, L690: Firmware = 3.3.10.4

ERRORLOG/1 @ initVirtualRC, L1029: Virtual RC is not supported on this platform!

STATUS/1 @ activate, L1239: version 0x3030A04

STATUS/1 @ activate, L1252: Activation successful

STATUS/1 @ verify, L245: Verify subscription successful.
STATUS/1 @ initGimbal, L850: Checking if gimbal is connected ...
STATUS/1 @ startPackage, L351: Start package 0 result: 0.
STATUS/1 @ startPackage, L353: Package 0 info: freq=50, nTopics=1.

STATUS/1 @ removePackage, L469: Remove package 0 successful.
STATUS/1 @ getErrorCodeMessage, L654: ∟
STATUS/1 @ getCMDIDSetControlMSG, L799: OBTAIN_CONTROL_SUCCESS

STATUS/1 @ init, L55: Attempting to open device /dev/ttyACM0 with baudrate 115200...

STATUS/1 @ init, L65: ...Serial started successfully.

STATUS/1 @ processReceivedData, L122: Successfully started/stopped simulated flight!

STATUS/1 @ reset, L568: Reset Subscription Successful.
```

After this launch the DJI ROS node:

```
rock64@rock64:~$ roslaunch dji_sdk sdk.launch
... logging to /home/rock64/.ros/log/35fc9908-aa97-11e8-b28e-86e0c0eafaa9/roslaunch-rock64-2467.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://rock64:34693/

SUMMARY
========

PARAMETERS
 * /dji_sdk/align_time: False
 * /dji_sdk/app_id: 1060581
 * /dji_sdk/app_version: 1
 * /dji_sdk/baud_rate: 230400
 * /dji_sdk/enc_key: 4844426e51fd869cc...
 * /dji_sdk/serial_name: /dev/ttyUSB0
 * /dji_sdk/use_broadcast: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /
    dji_sdk (dji_sdk/dji_sdk_node)

auto-starting new master
process[master]: started with pid [2477]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 35fc9908-aa97-11e8-b28e-86e0c0eafaa9
process[rosout-1]: started with pid [2495]
started core service [/rosout]
process[dji_sdk-2]: started with pid [2498]
[ INFO] [1535442710.035046008]: Advanced Sensing is Enabled on M210.

STATUS/1 @ init, L55: Attempting to open device /dev/ttyUSB0 with baudrate 230400...

STATUS/1 @ init, L65: ...Serial started successfully.

STATUS/1 @ parseDroneVersionInfo, L706: Device Serial No. = 095XF7C002024S

STATUS/1 @ parseDroneVersionInfo, L708: Hardware = PM410

STATUS/1 @ parseDroneVersionInfo, L709: Firmware = 3.3.10.4

ERRORLOG/1 @ initVirtualRC, L1067: Virtual RC is not supported on this platform!

STATUS/1 @ init, L49: Looking for USB device...

STATUS/1 @ init, L65: Found 11 USB devices, identifying DJI device...

STATUS/1 @ init, L83: Found a DJI device...

STATUS/1 @ init, L96: Attempting to open DJI USB device...

STATUS/1 @ init, L134: ...DJI USB device started successfully.

STATUS/1 @ activate, L1277: version 0x3030A04

STATUS/1 @ activate, L1290: Activation successful

STATUS/1 @ verify, L244: Verify subscription successful.
STATUS/1 @ initGimbal, L869: Checking if gimbal is connected ...
STATUS/1 @ startPackage, L350: Start package 0 result: 0.
STATUS/1 @ startPackage, L352: Package 0 info: freq=50, nTopics=1.

STATUS/1 @ removePackage, L468: Remove package 0 successful.[ INFO] [1535442716.539013379]: drone activated
[ INFO] [1535442717.018411613]: Use data subscription to get telemetry data!
[ INFO] [1535442717.018586609]: align_time_with_FC set to false. We will use ros time to time stamp messages!

STATUS/1 @ verify, L244: Verify subscription successful.
STATUS/1 @ startPackage, L350: Start package 2 result: 0.
STATUS/1 @ startPackage, L352: Package 2 info: freq=100, nTopics=3.

STATUS/1 @ startPackage, L350: Start package 1 result: 0.
STATUS/1 @ startPackage, L352: Package 1 info: freq=50, nTopics=14.

STATUS/1 @ startPackage, L350: Start package 0 result: 0.
STATUS/1 @ startPackage, L352: Package 0 info: freq=5, nTopics=6.

STATUS/1 @ startPackage, L350: Start package 3 result: 0.
STATUS/1 @ startPackage, L352: Package 3 info: freq=400, nTopics=1.
```

On DJI GO 4 mobile app drone shows itself on correct place on the map, and I can fly the drone using controller and it moves on the map, but when I try to get GPS information via ROS topics (/dji_sdk/gps_position or /dji_sdk/gps_health) I get nothing. So obviously the simulator mode works, GPS location comes from the flight controller so something in ROS node is causing the problem.

Other topics work fine (for example /dji_sdk/imu and /dji_sdk/battery_state).

One interesting thing is that if I try to output data from `/dji_sdk/gps_position` while ROS master node is launching, I get couple of correct GPS position messages but they stop right away. Here is video to see this in action: https://www.youtube.com/watch?v=7Qr8erRb10I

I have already opened ticket about this issue to DJI development support so they are investigating, but it would be interesting to know if anyone else is having similar issues, or if you get GPS position from ROS normally?

Edit: out of curiosity I complied the latest versions of Onboard-SDK (without advanced sensing) and Onboard-SDK-ROS for M100 to same Rock64 computer. When I launch the simulator mode via DJI Assistant 2 and launch the ROS node, I get GPS position from `/dji_sdk/gps_position` topic as usual. So this problem is only with M210.

I was able to reproduce the problem without simulator mode by starting M210 in a place that had GPS signal and the result was the same. DJI GO 4 showed the aircraft on correct real world position, but I didn't get any GPS information through ROS topics. While ROS node was starting I was able to get four messages from GPS position topic but nothing after that. Other topics (for example `/dji_sdk/imu`) work fine.

Here are the messages from `/dji_sdk/gps_position`:

```
header:
  seq: 0
  stamp:
    secs: 1535972002
    nsecs: 651632649
  frame_id: "/gps"
status:
  status: 0
  service: 0
latitude: 0.0
longitude: 0.0
altitude: -113.632270813
position_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
position_covariance_type: 0
---
header:
  seq: 1
  stamp:
    secs: 1535972002
    nsecs: 690251017
  frame_id: "/gps"
status:
  status: 0
  service: 0
latitude: 0.0
longitude: 0.0
altitude: -113.634155273
position_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
position_covariance_type: 0
---
header:
  seq: 2
  stamp:
    secs: 1535972002
    nsecs: 729843820
  frame_id: "/gps"
status:
  status: 0
  service: 0
latitude: 0.0
longitude: 0.0
altitude: -113.632392883
position_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
position_covariance_type: 0
---
header:
  seq: 3
  stamp:
    secs: 1535972002
    nsecs: 751594341
  frame_id: "/gps"
status:
  status: 0
  service: 0
latitude: 0.0
longitude: 0.0
altitude: -113.63785553
position_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
position_covariance_type: 0
```
